# 概要

Theanoの使い方 (1) シンボルと共有変数 - 人工知能に関する断創録
http://aidiary.hatenablog.com/entry/20150509/1431137590

# 目次

* シンボルによる数式の定義
* シグモイド関数の例
* 共有変数
* 線形回帰モデルの例

# シンボルによる数式の定義

In [5]:
import theano
import theano.tensor as T

In [8]:
# シンボルの生成
x = T.dscalar('x')
print(type(x))

<class 'theano.tensor.var.TensorVariable'>


In [9]:
# シンボルを組み立てて数式シンボルを定義
y = x ** 2
print(type(y))

<class 'theano.tensor.var.TensorVariable'>


In [10]:
# シンボルを使って関数を定義
f = theano.function(inputs=[x], outputs=y)
print(type(f))

<class 'theano.compile.function_module.Function'>


In [12]:
# 関数を使ってxに具体的な値を入れてyを計算
for i in range(1, 6):
    print(f(i))

1.0
4.0
9.0
16.0
25.0


# シグモイド関数の例

In [13]:
import theano
import theano.tensor as T

In [14]:
# シンボルを定義
x = T.dmatrix('x')

In [15]:
# シンボルを組み合わせて数式を定義
s = 1 / (1 + T.exp(-x))

In [16]:
# シンボルを使って関数化
sigmoid = theano.function(inputs=[x], outputs=s)

In [17]:
# 実数の値を使って計算
print(sigmoid([[0, 1], [-1, -2]]))

[[ 0.5         0.73105858]
 [ 0.26894142  0.11920292]]


# 共有変数

In [18]:
import numpy as np
import theano

In [21]:
# データを生成
data = np.array([[1, 2, 3], [4, 5, 6]], dtype=theano.config.floatX)
print(type(data))
print(data)

<class 'numpy.ndarray'>
[[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [20]:
# データを共有変数に読み込む
X = theano.shared(data, name='X', borrow=True)
print(type(X))
print(X.get_value())

<class 'theano.tensor.sharedvar.TensorSharedVariable'>
[[ 1.  2.  3.]
 [ 4.  5.  6.]]


# 線形回帰モデルの例

線形回帰モデルの式は、
$$y = Wx + b $$
で表される

In [22]:
import numpy as np
import theano
import theano.tensor as T

In [24]:
# 共有変数の定義
W = theano.shared(np.array([[1,2,3], [4,5,6]], dtype=theano.config.floatX),
                  name='W',
                  borrow=True)
b = theano.shared(np.array([1, 1], dtype=theano.config.floatX),
                  name='b',
                  borrow=True)

print(W.get_value())
print(b.get_value())

[[ 1.  2.  3.]
 [ 4.  5.  6.]]
[ 1.  1.]


In [25]:
# シンボルの生成
x = T.vector('x')

In [26]:
# シンボルと共有変数から数式を定義
y = T.dot(W, x) + b
print(type(y))

<class 'theano.tensor.var.TensorVariable'>


In [27]:
# 関数を定義
f = theano.function([x], y)

WARNING (theano.tensor.blas): We did not found a dynamic library into the library_dir of the library we use for blas. If you use ATLAS, make sure to compile it with dynamics library.
WARNING (theano.tensor.blas): We did not found a dynamic library into the library_dir of the library we use for blas. If you use ATLAS, make sure to compile it with dynamics library.


In [28]:
# 関数の使用
print(f([1, 1, 1]))

[  7.  16.]
